url: https://slgobinath.github.io
baseurl: /uget-chrome-wrapper

# Site settings
title: uGet Chrome Wrapper
email: slgobinath@gmail.com
description: "Integrate uGet Download Manager with Google Chrome, Chromium and Vivaldi"


# Team names, titles and social links
people:
- name: Gobinath
  pic: 1
  position: Developer
  social:
    - title: twitter
      url: https://twitter.com/lgobinath
    - title: linkedin
      url: https://lk.linkedin.com/in/gobinathl
    - title: google-plus
      url: https://plus.google.com/+Javahelpsplus
    - title: rss
      url: http://www.javahelps.com
    - title: medium
      url: https://medium.com/cognitio
    - title: github
      url: https://github.com/slgobinath
    - title: stack-overflow
      url: http://stackoverflow.com/users/4382663/gobinath

# Build settings
markdown: kramdown
permalink: pretty